name: Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    uses: nexomis/nf-test-workflow/.github/workflows/nf-test.yml@main
    with:
      nextflow_version: '25.04.3'
